 * Serving Flask app 'api'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://62.67.51.161:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 242-551-208
45.227.254.49 - - [16/May/2024 07:34:05] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*Ã \x00\x00\x00\x00\x00Cookie:')
45.227.254.49 - - [16/May/2024 07:34:05] "[35m[1m\x03\x00\x00/*Ã \x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
98.96.193.34 - - [16/May/2024 09:04:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 32, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
98.96.193.34 - - [16/May/2024 09:04:18] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 32, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
74.50.67.178 - - [16/May/2024 10:31:12] "[35m[1mHEAD / HTTP/1.0[0m" 500 -
45.95.169.184 - - [16/May/2024 12:11:22] code 400, message Bad HTTP/0.9 request type ('\x00\x00\x00\x11\x00\x00\x01Ã©\x00\x01\x00\x00\x00Ã¿Ã¿Ã¿Ã¿\x01\x00\x00\x00\x00\x00\x00\x00')
45.95.169.184 - - [16/May/2024 12:11:22] "[35m[1m\x00\x00\x00\x11\x00\x00\x01Ã©\x00\x01\x00\x00\x00Ã¿Ã¿Ã¿Ã¿\x01\x00\x00\x00\x00\x00\x00\x00\x0c\x02\x00\x00\x00\x10MyCustomAssembly\x05\x01\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
98.96.193.42 - - [16/May/2024 12:43:40] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 32, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
98.96.193.42 - - [16/May/2024 12:43:41] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
{'model': {'target': 'cldm.cldm.ControlLDM', 'params': {'linear_start': 0.00085, 'linear_end': 0.012, 'num_timesteps_cond': 1, 'log_every_t': 200, 'timesteps': 1000, 'first_stage_key': 'image', 'first_stage_key_cond': ['agn', 'agn_mask', 'image_densepose'], 'cond_stage_key': 'cloth', 'control_key': 'cloth', 'image_size': 64, 'channels': 4, 'cond_stage_trainable': False, 'conditioning_key': 'crossattn', 'monitor': 'val/loss_simple_ema', 'scale_factor': 0.18215, 'use_ema': False, 'only_mid_control': False, 'use_VAEdownsample': True, 'use_lastzc': True, 'use_imageCLIP': True, 'use_pbe_weight': True, 'u_cond_percent': 0.2, 'use_attn_mask': False, 'control_stage_config': {'target': 'cldm.warping_cldm_network.NoZeroConvControlNet', 'params': {'image_size': 32, 'in_channels': 13, 'hint_channels': 3, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'cond_first_ch': 4}}, 'unet_config': {'target': 'cldm.warping_cldm_network.StableVITON', 'params': {'image_size': 32, 'in_channels': 13, 'out_channels': 4, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'dim_head_denorm': 1}}, 'first_stage_config': {'target': 'ldm.models.autoencoder.AutoencoderKL', 'params': {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig': {'double_z': True, 'z_channels': 4, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}, 'lossconfig': {'target': 'torch.nn.Identity'}}}, 'validation_config': {'ddim_steps': 50, 'eta': 0.0, 'scale': 1.0}, 'cond_stage_config': {'target': 'ldm.modules.image_encoders.modules.FrozenCLIPImageEmbedder'}, 'img_H': 512, 'img_W': 384}}, 'dataset_name': 'VITONHDDataset', 'default_prompt': '', 'log_images_kwargs': {'unconditional_guidance_scale': 5.0}}
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 1039.33 M params.
beta scheduler name : linear
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
learnable vector gene
here
/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
0/1
Data shape for PLMS sampling is (1, 4, 64, 48)
Running PLMS Sampling with 1 timesteps
PLMS Sampler:   0%|          | 0/1 [00:00<?, ?it/s]PLMS Sampler: 100%|ââââââââââ| 1/1 [00:34<00:00, 34.76s/it]PLMS Sampler: 100%|ââââââââââ| 1/1 [00:34<00:00, 34.76s/it]
62.67.51.161 - - [16/May/2024 14:38:26] "GET /run_SV/2024-05-16_14-37-02 HTTP/1.1" 200 -
{'text': 'processed in 81.9 seconds'}
{'model': {'target': 'cldm.cldm.ControlLDM', 'params': {'linear_start': 0.00085, 'linear_end': 0.012, 'num_timesteps_cond': 1, 'log_every_t': 200, 'timesteps': 1000, 'first_stage_key': 'image', 'first_stage_key_cond': ['agn', 'agn_mask', 'image_densepose'], 'cond_stage_key': 'cloth', 'control_key': 'cloth', 'image_size': 64, 'channels': 4, 'cond_stage_trainable': False, 'conditioning_key': 'crossattn', 'monitor': 'val/loss_simple_ema', 'scale_factor': 0.18215, 'use_ema': False, 'only_mid_control': False, 'use_VAEdownsample': True, 'use_lastzc': True, 'use_imageCLIP': True, 'use_pbe_weight': True, 'u_cond_percent': 0.2, 'use_attn_mask': False, 'control_stage_config': {'target': 'cldm.warping_cldm_network.NoZeroConvControlNet', 'params': {'image_size': 32, 'in_channels': 13, 'hint_channels': 3, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'cond_first_ch': 4}}, 'unet_config': {'target': 'cldm.warping_cldm_network.StableVITON', 'params': {'image_size': 32, 'in_channels': 13, 'out_channels': 4, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'dim_head_denorm': 1}}, 'first_stage_config': {'target': 'ldm.models.autoencoder.AutoencoderKL', 'params': {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig': {'double_z': True, 'z_channels': 4, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}, 'lossconfig': {'target': 'torch.nn.Identity'}}}, 'validation_config': {'ddim_steps': 50, 'eta': 0.0, 'scale': 1.0}, 'cond_stage_config': {'target': 'ldm.modules.image_encoders.modules.FrozenCLIPImageEmbedder'}, 'img_H': 512, 'img_W': 384}}, 'dataset_name': 'VITONHDDataset', 'default_prompt': '', 'log_images_kwargs': {'unconditional_guidance_scale': 5.0}}
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 1039.33 M params.
beta scheduler name : linear
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
learnable vector gene
here
0/1
Data shape for PLMS sampling is (1, 4, 64, 48)
Running PLMS Sampling with 1 timesteps
PLMS Sampler:   0%|          | 0/1 [00:00<?, ?it/s]PLMS Sampler: 100%|ââââââââââ| 1/1 [00:35<00:00, 35.19s/it]PLMS Sampler: 100%|ââââââââââ| 1/1 [00:35<00:00, 35.19s/it]
62.67.51.161 - - [16/May/2024 14:42:06] "GET /run_SV/2024-05-16_14-40-43 HTTP/1.1" 200 -
198.235.24.193 - - [16/May/2024 19:06:00] "[35m[1mGET / HTTP/1.0[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 32, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.146.52 - - [16/May/2024 19:41:27] code 400, message Bad request version ('Ã\x14Ã')
167.94.146.52 - - [16/May/2024 19:41:27] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03Ã2\x9aÃ°cÃ´lnÃ¸ÃÃÃ;Ã§~e\x08;Ã{}Â¶Ã½Ã²Ã§\x17Ã³\x85Â¶\x84I\x93 #C~\x8b\x11<-ÃÂ¿JnZÂ wW\x85\x983Â½ÃXÃ¶Ã½ÃºÃ®1ÃKBhÂ¸\x1e\x00&ÃÂ¨ÃÂ©Ã/Ã0Ã+Ã,Ã\x13Ã\x09Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
167.94.146.52 - - [16/May/2024 19:41:30] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 32, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.146.52 - - [16/May/2024 19:41:34] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 32, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.146.52 - - [16/May/2024 19:41:34] code 505, message Invalid HTTP version (2.0)
167.94.146.52 - - [16/May/2024 19:41:34] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
 * Serving Flask app 'api'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://62.67.51.161:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 242-551-208
205.210.31.41 - - [16/May/2024 22:36:58] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
165.154.41.213 - - [17/May/2024 00:50:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
165.154.41.213 - - [17/May/2024 00:50:17] code 400, message Bad request version ('Ã\x13Ã')
165.154.41.213 - - [17/May/2024 00:50:17] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03\x1b<Ã°EV;ÃÃÃ¨Â¸Â¦}ÂµÃ«Ã¬Â¦$MÃÃÂº!Â°\x0fÃ®ÂµÃ-XÂ¼Sa Ã¨a`vÃ©/\x14h5\x8aÃ:Â°ÃÃUdÃ£ÃÃsÃAÃ¨\x94\x9aI()jÃ]\x00&Ã+Ã/Ã,Ã0ÃÂ©ÃÂ¨Ã\x09Ã\x13Ã[0m" HTTPStatus.BAD_REQUEST -
165.154.41.213 - - [17/May/2024 00:50:17] code 400, message Bad HTTP/0.9 request type ('t3')
165.154.41.213 - - [17/May/2024 00:50:17] "[35m[1mt3 12.1.2[0m" HTTPStatus.BAD_REQUEST -
165.154.206.223 - - [17/May/2024 01:05:53] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
165.154.206.223 - - [17/May/2024 01:05:54] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
165.154.206.223 - - [17/May/2024 01:05:54] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
165.154.206.223 - - [17/May/2024 01:05:54] "[33mGET /sitemap.xml HTTP/1.1[0m" 404 -
165.154.206.223 - - [17/May/2024 01:05:54] "[33mGET /robots.txt HTTP/1.1[0m" 404 -
162.142.125.226 - - [17/May/2024 02:26:11] code 400, message Bad request version ('Ã\x14Ã')
162.142.125.226 - - [17/May/2024 02:26:11] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03.\x95Ã½`XU Ã«nÂ¼qQ-\x85\x7f\x07Â¿\x84VvÃ©\x0bÃ¢Â«TQ>\x1fÂ¿Ã\x03( ÃÂ´Â¸\x10Â¥\x14Ã¯Ã\x80ÃÂ¤Â¯U~\x149Ã½B\x10[b^Ã±ÃcÃ)Â¬|\x8a\x1d\x02\x00&ÃÂ¨ÃÂ©Ã/Ã0Ã+Ã,Ã\x13Ã\x09Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
162.142.125.226 - - [17/May/2024 02:26:15] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
162.142.125.226 - - [17/May/2024 02:26:20] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
162.142.125.226 - - [17/May/2024 02:26:20] code 505, message Invalid HTTP version (2.0)
162.142.125.226 - - [17/May/2024 02:26:20] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
199.45.154.78 - - [17/May/2024 05:12:33] code 400, message Bad request version ('Ã\x14Ã')
199.45.154.78 - - [17/May/2024 05:12:33] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03Ã¬WXÃ¾Ã\x05Â¼dÃ+!\x15Â²Ãº`Ã¥Ã\x0bÃ°Âª/Ã´/5\x11tÂ´\x91Â©Ã¢\x80S \x147)\x1cÃ1\x95Ã\x8e\x80;\x06Ã\x82\x91ÃÃ\x12Â¸67A\x9eÂºÂ³ÃÃ\x8cÃ±'Â¯Ã»\x00&ÃÂ¨ÃÂ©Ã/Ã0Ã+Ã,Ã\x13Ã\x09Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
167.94.138.124 - - [17/May/2024 05:42:57] code 400, message Bad request version ('^\xad\x99\x81')
167.94.138.124 - - [17/May/2024 05:42:57] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03Â¯\\Ã¿Ã¥\x15w\x17aB\x9f\x0cE\x96\x16ÃÃ\x89\x80ÃÃ®ÃÂªR\x054'\x89ÂµÃ©9Â³\x98 Ã\x92\x04Â¯Ã Ã¢=\x80\x8bÃ·ÃÃr\x16Ã\x1c^Â­\x99\x81[0m" HTTPStatus.BAD_REQUEST -
167.94.138.124 - - [17/May/2024 05:43:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.124 - - [17/May/2024 05:43:03] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.124 - - [17/May/2024 05:43:04] code 505, message Invalid HTTP version (2.0)
167.94.138.124 - - [17/May/2024 05:43:04] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
45.156.129.46 - - [17/May/2024 07:34:27] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
{'model': {'target': 'cldm.cldm.ControlLDM', 'params': {'linear_start': 0.00085, 'linear_end': 0.012, 'num_timesteps_cond': 1, 'log_every_t': 200, 'timesteps': 1000, 'first_stage_key': 'image', 'first_stage_key_cond': ['agn', 'agn_mask', 'image_densepose'], 'cond_stage_key': 'cloth', 'control_key': 'cloth', 'image_size': 64, 'channels': 4, 'cond_stage_trainable': False, 'conditioning_key': 'crossattn', 'monitor': 'val/loss_simple_ema', 'scale_factor': 0.18215, 'use_ema': False, 'only_mid_control': False, 'use_VAEdownsample': True, 'use_lastzc': True, 'use_imageCLIP': True, 'use_pbe_weight': True, 'u_cond_percent': 0.2, 'use_attn_mask': False, 'control_stage_config': {'target': 'cldm.warping_cldm_network.NoZeroConvControlNet', 'params': {'image_size': 32, 'in_channels': 13, 'hint_channels': 3, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'cond_first_ch': 4}}, 'unet_config': {'target': 'cldm.warping_cldm_network.StableVITON', 'params': {'image_size': 32, 'in_channels': 13, 'out_channels': 4, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'dim_head_denorm': 1}}, 'first_stage_config': {'target': 'ldm.models.autoencoder.AutoencoderKL', 'params': {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig': {'double_z': True, 'z_channels': 4, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}, 'lossconfig': {'target': 'torch.nn.Identity'}}}, 'validation_config': {'ddim_steps': 50, 'eta': 0.0, 'scale': 1.0}, 'cond_stage_config': {'target': 'ldm.modules.image_encoders.modules.FrozenCLIPImageEmbedder'}, 'img_H': 512, 'img_W': 384}}, 'dataset_name': 'VITONHDDataset', 'default_prompt': '', 'log_images_kwargs': {'unconditional_guidance_scale': 5.0}}
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 1039.33 M params.
beta scheduler name : linear
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
learnable vector gene
here
/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
0/1
Data shape for PLMS sampling is (1, 4, 64, 48)
Running PLMS Sampling with 50 timesteps
PLMS Sampler:   0%|          | 0/50 [00:00<?, ?it/s]PLMS Sampler:   2%|â         | 1/50 [00:31<26:07, 31.98s/it]PLMS Sampler:   4%|â         | 2/50 [00:47<17:51, 22.33s/it]PLMS Sampler:   6%|â         | 3/50 [01:03<15:06, 19.28s/it]PLMS Sampler:   8%|â         | 4/50 [01:17<13:16, 17.31s/it]PLMS Sampler:  10%|â         | 5/50 [01:31<12:12, 16.29s/it]PLMS Sampler:  12%|ââ        | 6/50 [01:46<11:26, 15.61s/it]PLMS Sampler:  14%|ââ        | 7/50 [02:01<11:10, 15.60s/it]PLMS Sampler:  16%|ââ        | 8/50 [02:15<10:30, 15.01s/it]PLMS Sampler:  18%|ââ        | 9/50 [02:29<10:00, 14.66s/it]PLMS Sampler:  20%|ââ        | 10/50 [02:43<09:40, 14.51s/it]PLMS Sampler:  22%|âââ       | 11/50 [02:58<09:34, 14.74s/it]PLMS Sampler:  24%|âââ       | 12/50 [03:12<09:12, 14.53s/it]PLMS Sampler:  26%|âââ       | 13/50 [03:27<08:56, 14.50s/it]PLMS Sampler:  28%|âââ       | 14/50 [03:41<08:38, 14.40s/it]PLMS Sampler:  30%|âââ       | 15/50 [03:54<08:13, 14.11s/it]PLMS Sampler:  32%|ââââ      | 16/50 [04:07<07:45, 13.68s/it]PLMS Sampler:  34%|ââââ      | 17/50 [04:20<07:26, 13.54s/it]PLMS Sampler:  36%|ââââ      | 18/50 [04:34<07:16, 13.64s/it]PLMS Sampler:  38%|ââââ      | 19/50 [04:49<07:08, 13.82s/it]PLMS Sampler:  40%|ââââ      | 20/50 [05:02<06:56, 13.87s/it]PLMS Sampler:  42%|âââââ     | 21/50 [05:16<06:39, 13.79s/it]PLMS Sampler:  44%|âââââ     | 22/50 [05:30<06:27, 13.85s/it]PLMS Sampler:  46%|âââââ     | 23/50 [05:45<06:24, 14.25s/it]PLMS Sampler:  48%|âââââ     | 24/50 [06:00<06:14, 14.38s/it]PLMS Sampler:  50%|âââââ     | 25/50 [06:15<06:04, 14.60s/it]PLMS Sampler:  52%|ââââââ    | 26/50 [06:29<05:48, 14.53s/it]PLMS Sampler:  54%|ââââââ    | 27/50 [06:42<05:23, 14.04s/it]PLMS Sampler:  56%|ââââââ    | 28/50 [06:56<05:06, 13.94s/it]PLMS Sampler:  58%|ââââââ    | 29/50 [07:10<04:52, 13.91s/it]PLMS Sampler:  60%|ââââââ    | 30/50 [07:22<04:28, 13.42s/it]PLMS Sampler:  62%|âââââââ   | 31/50 [07:36<04:19, 13.66s/it]PLMS Sampler:  64%|âââââââ   | 32/50 [07:49<04:01, 13.44s/it]PLMS Sampler:  66%|âââââââ   | 33/50 [08:03<03:47, 13.37s/it]PLMS Sampler:  68%|âââââââ   | 34/50 [08:16<03:33, 13.37s/it]PLMS Sampler:  70%|âââââââ   | 35/50 [08:29<03:17, 13.15s/it]PLMS Sampler:  72%|ââââââââ  | 36/50 [08:42<03:04, 13.16s/it]PLMS Sampler:  74%|ââââââââ  | 37/50 [08:55<02:50, 13.08s/it]PLMS Sampler:  76%|ââââââââ  | 38/50 [09:09<02:40, 13.39s/it]PLMS Sampler:  78%|ââââââââ  | 39/50 [09:22<02:26, 13.27s/it]PLMS Sampler:  80%|ââââââââ  | 40/50 [09:35<02:13, 13.34s/it]PLMS Sampler:  82%|âââââââââ | 41/50 [09:48<01:58, 13.12s/it]PLMS Sampler:  84%|âââââââââ | 42/50 [10:02<01:47, 13.47s/it]PLMS Sampler:  86%|âââââââââ | 43/50 [10:15<01:33, 13.42s/it]PLMS Sampler:  88%|âââââââââ | 44/50 [10:28<01:19, 13.30s/it]PLMS Sampler:  90%|âââââââââ | 45/50 [10:41<01:05, 13.13s/it]PLMS Sampler:  92%|ââââââââââ| 46/50 [10:55<00:53, 13.39s/it]PLMS Sampler:  94%|ââââââââââ| 47/50 [11:08<00:39, 13.24s/it]PLMS Sampler:  96%|ââââââââââ| 48/50 [11:22<00:26, 13.36s/it]PLMS Sampler:  98%|ââââââââââ| 49/50 [11:35<00:13, 13.39s/it]PLMS Sampler: 100%|ââââââââââ| 50/50 [11:48<00:00, 13.30s/it]PLMS Sampler: 100%|ââââââââââ| 50/50 [11:48<00:00, 14.17s/it]
62.67.51.161 - - [17/May/2024 09:08:35] "GET /run_SV/2024-05-17_08-55-54 HTTP/1.1" 200 -
45.227.254.49 - - [17/May/2024 15:02:46] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*Ã \x00\x00\x00\x00\x00Cookie:')
45.227.254.49 - - [17/May/2024 15:02:46] "[35m[1m\x03\x00\x00/*Ã \x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
198.235.24.124 - - [17/May/2024 17:52:57] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
198.235.24.164 - - [18/May/2024 02:38:54] "[35m[1mGET / HTTP/1.0[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
174.138.61.44 - - [18/May/2024 04:39:40] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.145.96 - - [18/May/2024 04:46:43] code 400, message Bad request version ('Ã\x14Ã')
167.94.145.96 - - [18/May/2024 04:46:43] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03Â¨qÂ£\x11ÃmÃÃ°k Â´V\x8e):/sq\x03Â¯\x1e\x878YÃ¨\x06dÃ·Ã­\x99jÃ§ @ÃÃ\x88\x9e|ÃlÃ\x0cÂ¯r\x86ÃA\x9cRWGÃ´Ã\x07Ã´ÃqRÂ­ Ã¶\x9fkS\x00&ÃÂ¨ÃÂ©Ã/Ã0Ã+Ã,Ã\x13Ã\x09Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
167.94.145.96 - - [18/May/2024 04:46:46] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.145.96 - - [18/May/2024 04:46:49] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.145.96 - - [18/May/2024 04:46:49] code 505, message Invalid HTTP version (2.0)
167.94.145.96 - - [18/May/2024 04:46:49] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
 * Serving Flask app 'api'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://62.67.51.161:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 242-551-208
45.128.232.98 - - [20/May/2024 11:17:18] code 400, message Bad request syntax ('JDWP-Handshake')
45.128.232.98 - - [20/May/2024 11:17:18] "[35m[1mJDWP-Handshake[0m" HTTPStatus.BAD_REQUEST -
167.94.138.120 - - [20/May/2024 11:23:11] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.120 - - [20/May/2024 11:23:12] code 505, message Invalid HTTP version (2.0)
167.94.138.120 - - [20/May/2024 11:23:12] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
205.210.31.205 - - [20/May/2024 14:31:33] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.119 - - [20/May/2024 14:35:52] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.119 - - [20/May/2024 14:35:52] code 505, message Invalid HTTP version (2.0)
167.94.138.119 - - [20/May/2024 14:35:52] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
162.142.125.215 - - [20/May/2024 14:37:41] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
162.142.125.215 - - [20/May/2024 14:37:42] code 505, message Invalid HTTP version (2.0)
162.142.125.215 - - [20/May/2024 14:37:42] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
 * Serving Flask app 'api'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://62.67.51.161:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 242-551-208
45.227.254.8 - - [21/May/2024 09:42:46] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*Ã \x00\x00\x00\x00\x00Cookie:')
45.227.254.8 - - [21/May/2024 09:42:46] "[35m[1m\x03\x00\x00/*Ã \x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
205.209.125.225 - - [21/May/2024 19:18:27] "[35m[1mHEAD / HTTP/1.0[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
205.209.125.225 - - [21/May/2024 19:37:30] "[35m[1mHEAD / HTTP/1.0[0m" 500 -
159.65.63.33 - - [22/May/2024 00:18:07] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x03\x01\x9c\x01\x00\x01\x98\x03\x03Âª\x83ÃÂ´\x08')
159.65.63.33 - - [22/May/2024 00:18:07] "[35m[1m\x16\x03\x03\x01\x9c\x01\x00\x01\x98\x03\x03Âª\x83ÃÂ´\x08\x1fbTÃ¿Ã³Ã\x04CJ.hYJÃ¿\x88\x04tÃ¢xÂ¹Z!9c[0m" HTTPStatus.BAD_REQUEST -
159.65.63.33 - - [22/May/2024 00:18:07] code 400, message Bad request version ('\x9d9Ã Ã¼=X@a\x89\x11_RÃ¯\x0f^rÃHXÃÃ¯.Â©Q`ÃKÃÃÂ£\\H\x00\x8c')
159.65.63.33 - - [22/May/2024 00:18:07] "[35m[1m\x16\x03\x03\x01\x9c\x01\x00\x01\x98\x03\x03\x18VxÂ¡Ã¢\x88Ã\x08s\x9bÃ \x0b\x90z\x0b\x96s7\x1bÂºÃ°\x17,ÃPÂ¢Ã²\x14'VÂ­Ã \x9d9Ã Ã¼=X@a\x89\x11_RÃ¯\x0f^rÃHXÃÃ¯.Â©Q`ÃKÃÃÂ£\\H\x00\x8c[0m" HTTPStatus.BAD_REQUEST -
159.65.63.33 - - [22/May/2024 00:18:07] code 400, message Bad request version ('\x00HÂªÂªÃ\x12Ã\x07Ã\x14\x13\x01\x13\x02ÃÂ©ÃsÃrÃ,ÃÂ¯Ã\xadÃ$Ã')
159.65.63.33 - - [22/May/2024 00:18:07] "[35m[1m\x16\x03\x03\x01X\x01\x00\x01T\x03\x03\x00\x89ÃÃ·|Â¸O|Ã\x85ZÃº#$U\x15nX\x1d$Â¡p\x9d\x95\x879\x9bMÃ Â§Â½] ,?Ã¦sÃ\x17=\x1aVÃ¤oSÃÃÃ©Âº/\x8aÃÂ¨cÂµjÂ³-\x9fi\x07\x8f\x0bÂµ\x0b\x00HÂªÂªÃ\x12Ã\x07Ã\x14\x13\x01\x13\x02ÃÂ©ÃsÃrÃ,ÃÂ¯ÃÂ­Ã$Ã[0m" HTTPStatus.BAD_REQUEST -
159.65.63.33 - - [22/May/2024 00:18:07] code 400, message Bad request version ("\x13Ã,ÃEW,\x9cVÂ¯Â¤\x8bÃ¤J)Ã¹LOÃ1iÃ~F\x9d&Â¤ÃÃ¤Ã¿\x00FÂºÂºÃ\x13Ã'Ã/Ã\x14Ã(Ã0Ã`ÃaÃvÃwÃÂ¨\x13\x05\x13\x04\x13\x03Ã\x13Ã\x11\x00")
159.65.63.33 - - [22/May/2024 00:18:07] "[35m[1m\x16\x03\x03\x01J\x01\x00\x01F\x03\x03Ã\x9b`tgÃÂ§0\x08\\ÃÂ«Â²\x1d\x9cÃi\x89+,Ã³Ã¤\x81oÃ\x18Ã©D\x9aÂª\x07. N\x1d\x13Ã,ÃEW,\x9cVÂ¯Â¤\x8bÃ¤J)Ã¹LOÃ1iÃ~F\x9d&Â¤ÃÃ¤Ã¿\x00FÂºÂºÃ\x13Ã'Ã/Ã\x14Ã(Ã0Ã`ÃaÃvÃwÃÂ¨\x13\x05\x13\x04\x13\x03Ã\x13Ã\x11\x00[0m" HTTPStatus.BAD_REQUEST -
159.65.63.33 - - [22/May/2024 00:18:08] code 400, message Bad request version ("P:qÃl\x9a\x04BÂ±\xad\x13ÃµÃ¸Ã­Ã¼tf5\x1b~\x8a\x9f\x96%Ã\x13\x00\x8aÃ\x12Ã\x13Ã\x07Ã'Ã\x14Ã/\x13\x01Ã\x14\x13\x02Ã(ÃÂ©Ã0ÃsÃ`ÃrÃaÃ,ÃvÃÂ¯ÃwÃ\xadÃÂ¨Ã$\x13\x05Ã")
159.65.63.33 - - [22/May/2024 00:18:08] "[35m[1m\x16\x03\x03\x01s\x01\x00\x01o\x03\x03\x1aÃxÂ©\x80j8\x00Ã¾ÃÃ¨E\x13- &Â¦Ã³v\x9f\x1fÃÃ\x8e\x05r.ÃÂ¯_Â¸, \x03\x87\x03M\x10 P:qÃl\x9a\x04BÂ±Â­\x13ÃµÃ¸Ã­Ã¼tf5\x1b~\x8a\x9f\x96%Ã\x13\x00\x8aÃ\x12Ã\x13Ã\x07Ã'Ã\x14Ã/\x13\x01Ã\x14\x13\x02Ã(ÃÂ©Ã0ÃsÃ`ÃrÃaÃ,ÃvÃÂ¯ÃwÃÂ­ÃÂ¨Ã$\x13\x05Ã[0m" HTTPStatus.BAD_REQUEST -
159.65.63.33 - - [22/May/2024 00:18:08] code 400, message Bad request version ('Ã#ÃÂ¬ÃÂ®Ã+Ã')
159.65.63.33 - - [22/May/2024 00:18:08] "[35m[1m\x16\x03\x02\x01\x9c\x01\x00\x01\x98\x03\x02Y(\x94]WgÃªP3IÂ¦Â·}Ã¹=Ã\x97Â«^Â¨\x0eÃmÂ´Ã±Â·Ã§ÃyjRÂ­ Ã§\x86Ã­hÃÃ\x97ÃÂ¥ÃÃÂ½\x8eÃÃ³Â¾Â¯Ã­4yÃ¾\x17-Â¶h\x0f\x9e\x8cMÃ£Ã¡\x1b\x00\x8cZZ\x00\x16\x003\x00gÃ\x9eÃÂ¢\x00\x9e\x009\x00kÃ\x9fÃÂ£\x00\x9f\x00E\x00Â¾\x00\x88\x00Ã\x00\x9aÃ\x08Ã\x09Ã#ÃÂ¬ÃÂ®Ã+Ã[0m" HTTPStatus.BAD_REQUEST -
159.65.63.33 - - [22/May/2024 00:18:08] code 400, message Bad request version ('Ã#ÃÂ¬ÃÂ®Ã+Ã')
159.65.63.33 - - [22/May/2024 00:18:08] "[35m[1m\x16\x03\x01\x01Â©\x01\x00\x01Â¥\x03\x03.\x0dÃÃ»ZÃº\x05|Mr>ÃµyTÃlÃ©\x03Ã\x01LÃ\x02Lurk\x0eÃÃZÃ Â¡\x8a\x9d\x915Ã¡iÂ¾Ãª<\x85Â¸0Â²Â¼Ã«oqx\x90\x16LPdÂªÂ»@`\x98Ã¨o\x9e\x00\x8c\x9a\x9a\x00\x16\x003\x00gÃ\x9eÃÂ¢\x00\x9e\x009\x00kÃ\x9fÃÂ£\x00\x9f\x00E\x00Â¾\x00\x88\x00Ã\x00\x9aÃ\x08Ã\x09Ã#ÃÂ¬ÃÂ®Ã+Ã[0m" HTTPStatus.BAD_REQUEST -
159.65.63.33 - - [22/May/2024 00:18:08] code 400, message Bad request version ('Ã\x9c\x00<\x00/\x00')
159.65.63.33 - - [22/May/2024 00:18:08] "[35m[1m\x16\x03\x01\x01Â©\x01\x00\x01Â¥\x03\x03\x96?\x17FÃ¡\x05F\x86\x9caÃ¸`7(\x07\x94Â¥ÃÃº\x0b\x08ÂµÃ¢\x91Â¬Â®\x08g_\x7f\x1eo Ã E\x0b\x12KÂ¸Â®\x13Ã«!ÃRÃ¸0Ã\x11l\x00\x8acÃÃZDv\x02\x0e\x11\x04%Ã\x88\x00\x8czz\x00\x05\x00\x04\x00\x07\x00Ã\x00\x84\x00Âº\x00A\x00\x9dÃÂ¡Ã\x9d\x00=\x005\x00\x9cÃÂ Ã\x9c\x00<\x00/\x00[0m" HTTPStatus.BAD_REQUEST -
159.65.63.33 - - [22/May/2024 00:18:08] code 400, message Bad request version ('Ã#ÃÂ¬ÃÂ®Ã+Ã')
159.65.63.33 - - [22/May/2024 00:18:08] "[35m[1m\x16\x03\x01\x01\x9f\x01\x00\x01\x9b\x03\x03\x0egÂ¿8Â¬;Â¥ ^\x92)!Ã¥*\x9bÃ¤ÃÃÃ½UWÂ´Â°ÃÂ¡\x15Ã²\x99Ã\x1cÂ«\x99 KÃTnÃ§Â¯Ã¤ZÃÃ¡Ã£\x82Ã·\x11AVÂº\x18Ã®\x7fÃ¾\x93\x0b\x9bÂ±w\x88L\x0d@Ã±2\x00\x82ÂºÂº\x00\x16\x003\x00gÃ\x9eÃÂ¢\x00\x9e\x009\x00kÃ\x9fÃÂ£\x00\x9f\x00E\x00Â¾\x00\x88\x00Ã\x00\x9aÃ\x08Ã\x09Ã#ÃÂ¬ÃÂ®Ã+Ã[0m" HTTPStatus.BAD_REQUEST -
159.65.63.33 - - [22/May/2024 00:18:08] code 400, message Bad request version (";2Ãx\x08ÃÂ½'OÃÂ¯\x13U\x96\x865gH&hÃ°&<JÂ¶ÃÂ¤Ã«\x9cÂ¾\x00\x8aÃ\x12Ã\x13Ã\x07Ã'Ã\x14Ã/\x13\x01Ã\x14\x13\x02Ã(ÃÂ©Ã0ÃsÃ`ÃrÃaÃ,ÃvÃÂ¯ÃwÃ\xadÃÂ¨Ã$\x13\x05Ã")
159.65.63.33 - - [22/May/2024 00:18:08] "[35m[1m\x16\x03\x01\x01\x8e\x01\x00\x01\x8a\x03\x03#!ÃÃ³Sfg~ÃÃ\x1fÃ²QÂ°\x1c]\x88Ã¯yÂ¢.\x0f\x08Ã¢L>Â£i:ÂªZÃ¤ Â½\x0d;2Ãx\x08ÃÂ½'OÃÂ¯\x13U\x96\x865gH&hÃ°&<JÂ¶ÃÂ¤Ã«\x9cÂ¾\x00\x8aÃ\x12Ã\x13Ã\x07Ã'Ã\x14Ã/\x13\x01Ã\x14\x13\x02Ã(ÃÂ©Ã0ÃsÃ`ÃrÃaÃ,ÃvÃÂ¯ÃwÃÂ­ÃÂ¨Ã$\x13\x05Ã[0m" HTTPStatus.BAD_REQUEST -
64.227.42.8 - - [22/May/2024 00:33:43] code 400, message Bad request version ("Ã¸,Ã'ÃfÂ°Ã\x8a@\x00\x01<Ã\x14Ã\x13Ã\x15Ã0Ã,Ã(Ã$Ã\x14Ã")
64.227.42.8 - - [22/May/2024 00:33:43] "[35m[1m\x16\x03\x01\x01Ã»\x01\x00\x01Ã·\x03\x03\x982sÃ»Ã¸BSLVeÃ\x1d;[ÃÃi\x82\x1eCÃ\x0dÃ¸,Ã'ÃfÂ°Ã\x8a@\x00\x01<Ã\x14Ã\x13Ã\x15Ã0Ã,Ã(Ã$Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
198.235.24.136 - - [22/May/2024 02:44:58] "[35m[1mGET / HTTP/1.0[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.146.48 - - [22/May/2024 02:49:29] code 400, message Bad request version ('Ã\x14Ã')
167.94.146.48 - - [22/May/2024 02:49:29] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03\x06)\x19bÃ«ÃºÃ¬ÃÃ²Ã·[Ã·Ã¶Â¢Ã\x9a\x0bÂ¯;\x14Â³'\x1eÂ¯ÃiZ\x98\x80HÃ¢\x13 \\XÃÃ½y\x8eÂ­ÃºÂ£ÃÃo73\x9fU3\x8b`\x1fÃÂªQOÂ°ÃOT\x87Â¥Â³Â±\x00&ÃÂ¨ÃÂ©Ã/Ã0Ã+Ã,Ã\x13Ã\x09Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
167.94.146.48 - - [22/May/2024 02:49:32] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.146.48 - - [22/May/2024 02:49:35] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.146.48 - - [22/May/2024 02:49:35] code 505, message Invalid HTTP version (2.0)
167.94.146.48 - - [22/May/2024 02:49:35] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
167.248.133.121 - - [22/May/2024 03:39:00] code 400, message Bad request version ('Ã\x14Ã')
167.248.133.121 - - [22/May/2024 03:39:00] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03\x98ÃP\x98wÂ¯Â£\x1cQÃ£\x8dg*ÃJÃµÃÃÃ6MHXÃ\x13\x9fÂ¬TÃ\x9ebÃ ÃªA\x03\x09)\x96Ã¤\\ÃVqaÂ¬8lNÂ¹\x90XÃ©Ã¢9\x1b\x08Ã\x9dÂ»\x9c[c Ã«\x00&ÃÂ¨ÃÂ©Ã/Ã0Ã+Ã,Ã\x13Ã\x09Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
167.248.133.121 - - [22/May/2024 03:39:04] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.248.133.121 - - [22/May/2024 03:39:08] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.248.133.121 - - [22/May/2024 03:39:09] code 505, message Invalid HTTP version (2.0)
167.248.133.121 - - [22/May/2024 03:39:09] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
{'model': {'target': 'cldm.cldm.ControlLDM', 'params': {'linear_start': 0.00085, 'linear_end': 0.012, 'num_timesteps_cond': 1, 'log_every_t': 200, 'timesteps': 1000, 'first_stage_key': 'image', 'first_stage_key_cond': ['agn', 'agn_mask', 'image_densepose'], 'cond_stage_key': 'cloth', 'control_key': 'cloth', 'image_size': 64, 'channels': 4, 'cond_stage_trainable': False, 'conditioning_key': 'crossattn', 'monitor': 'val/loss_simple_ema', 'scale_factor': 0.18215, 'use_ema': False, 'only_mid_control': False, 'use_VAEdownsample': True, 'use_lastzc': True, 'use_imageCLIP': True, 'use_pbe_weight': True, 'u_cond_percent': 0.2, 'use_attn_mask': False, 'control_stage_config': {'target': 'cldm.warping_cldm_network.NoZeroConvControlNet', 'params': {'image_size': 32, 'in_channels': 13, 'hint_channels': 3, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'cond_first_ch': 4}}, 'unet_config': {'target': 'cldm.warping_cldm_network.StableVITON', 'params': {'image_size': 32, 'in_channels': 13, 'out_channels': 4, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'dim_head_denorm': 1}}, 'first_stage_config': {'target': 'ldm.models.autoencoder.AutoencoderKL', 'params': {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig': {'double_z': True, 'z_channels': 4, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}, 'lossconfig': {'target': 'torch.nn.Identity'}}}, 'validation_config': {'ddim_steps': 50, 'eta': 0.0, 'scale': 1.0}, 'cond_stage_config': {'target': 'ldm.modules.image_encoders.modules.FrozenCLIPImageEmbedder'}, 'img_H': 512, 'img_W': 384}}, 'dataset_name': 'VITONHDDataset', 'default_prompt': '', 'log_images_kwargs': {'unconditional_guidance_scale': 5.0}}
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 1039.33 M params.
beta scheduler name : linear
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
learnable vector gene
here
/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
0/1
Data shape for PLMS sampling is (1, 4, 64, 48)
Running PLMS Sampling with 50 timesteps
PLMS Sampler:   0%|          | 0/50 [00:00<?, ?it/s]PLMS Sampler:   2%|â         | 1/50 [00:35<28:41, 35.14s/it]PLMS Sampler:   4%|â         | 2/50 [00:50<19:01, 23.78s/it]PLMS Sampler:   6%|â         | 3/50 [01:06<15:48, 20.18s/it]PLMS Sampler:   8%|â         | 4/50 [01:23<14:21, 18.73s/it]PLMS Sampler:  10%|â         | 5/50 [01:38<13:11, 17.58s/it]PLMS Sampler:  12%|ââ        | 6/50 [01:55<12:32, 17.11s/it]PLMS Sampler:  14%|ââ        | 7/50 [02:11<12:01, 16.79s/it]PLMS Sampler:  16%|ââ        | 8/50 [02:27<11:34, 16.53s/it]PLMS Sampler:  18%|ââ        | 9/50 [02:42<11:07, 16.27s/it]PLMS Sampler:  20%|ââ        | 10/50 [02:58<10:36, 15.92s/it]PLMS Sampler:  22%|âââ       | 11/50 [03:12<10:07, 15.57s/it]PLMS Sampler:  24%|âââ       | 12/50 [03:28<09:58, 15.75s/it]PLMS Sampler:  26%|âââ       | 13/50 [03:44<09:44, 15.80s/it]PLMS Sampler:  28%|âââ       | 14/50 [04:00<09:21, 15.60s/it]PLMS Sampler:  30%|âââ       | 15/50 [04:15<09:02, 15.51s/it]PLMS Sampler:  32%|ââââ      | 16/50 [04:30<08:47, 15.50s/it]PLMS Sampler:  34%|ââââ      | 17/50 [04:45<08:20, 15.16s/it]PLMS Sampler:  36%|ââââ      | 18/50 [04:59<07:59, 14.97s/it]PLMS Sampler:  38%|ââââ      | 19/50 [05:15<07:50, 15.19s/it]PLMS Sampler:  40%|ââââ      | 20/50 [05:31<07:41, 15.39s/it]PLMS Sampler:  42%|âââââ     | 21/50 [05:46<07:26, 15.41s/it]PLMS Sampler:  44%|âââââ     | 22/50 [06:02<07:14, 15.50s/it]PLMS Sampler:  46%|âââââ     | 23/50 [06:17<06:57, 15.47s/it]PLMS Sampler:  48%|âââââ     | 24/50 [06:32<06:38, 15.34s/it]PLMS Sampler:  50%|âââââ     | 25/50 [06:46<06:11, 14.84s/it]PLMS Sampler:  52%|ââââââ    | 26/50 [07:02<06:02, 15.11s/it]PLMS Sampler:  54%|ââââââ    | 27/50 [07:18<05:51, 15.29s/it]PLMS Sampler:  56%|ââââââ    | 28/50 [07:32<05:33, 15.17s/it]PLMS Sampler:  58%|ââââââ    | 29/50 [07:48<05:21, 15.31s/it]PLMS Sampler:  60%|ââââââ    | 30/50 [08:04<05:07, 15.40s/it]PLMS Sampler:  62%|âââââââ   | 31/50 [08:19<04:53, 15.43s/it]PLMS Sampler:  64%|âââââââ   | 32/50 [08:34<04:37, 15.40s/it]PLMS Sampler:  66%|âââââââ   | 33/50 [08:50<04:21, 15.39s/it]PLMS Sampler:  68%|âââââââ   | 34/50 [09:05<04:06, 15.40s/it]PLMS Sampler:  70%|âââââââ   | 35/50 [09:20<03:49, 15.27s/it]PLMS Sampler:  72%|ââââââââ  | 36/50 [09:44<04:07, 17.69s/it]PLMS Sampler:  74%|ââââââââ  | 37/50 [10:14<04:38, 21.45s/it]PLMS Sampler:  76%|ââââââââ  | 38/50 [10:43<04:46, 23.89s/it]PLMS Sampler:  78%|ââââââââ  | 39/50 [11:12<04:37, 25.24s/it]PLMS Sampler:  80%|ââââââââ  | 40/50 [11:40<04:22, 26.26s/it]PLMS Sampler:  82%|âââââââââ | 41/50 [12:04<03:48, 25.41s/it]PLMS Sampler:  84%|âââââââââ | 42/50 [12:20<03:01, 22.69s/it]PLMS Sampler:  86%|âââââââââ | 43/50 [12:36<02:24, 20.60s/it]PLMS Sampler:  88%|âââââââââ | 44/50 [12:50<01:52, 18.76s/it]PLMS Sampler:  90%|âââââââââ | 45/50 [13:06<01:29, 17.86s/it]PLMS Sampler:  92%|ââââââââââ| 46/50 [13:21<01:07, 16.86s/it]PLMS Sampler:  94%|ââââââââââ| 47/50 [13:36<00:49, 16.43s/it]PLMS Sampler:  96%|ââââââââââ| 48/50 [13:52<00:32, 16.13s/it]PLMS Sampler:  98%|ââââââââââ| 49/50 [14:08<00:16, 16.14s/it]PLMS Sampler: 100%|ââââââââââ| 50/50 [14:23<00:00, 16.04s/it]PLMS Sampler: 100%|ââââââââââ| 50/50 [14:23<00:00, 17.28s/it]
62.67.51.161 - - [22/May/2024 07:29:21] "GET /run_SV/2024-05-22_07-14-10 HTTP/1.1" 200 -
{'text': 'processed in 907.18 seconds'}
{'model': {'target': 'cldm.cldm.ControlLDM', 'params': {'linear_start': 0.00085, 'linear_end': 0.012, 'num_timesteps_cond': 1, 'log_every_t': 200, 'timesteps': 1000, 'first_stage_key': 'image', 'first_stage_key_cond': ['agn', 'agn_mask', 'image_densepose'], 'cond_stage_key': 'cloth', 'control_key': 'cloth', 'image_size': 64, 'channels': 4, 'cond_stage_trainable': False, 'conditioning_key': 'crossattn', 'monitor': 'val/loss_simple_ema', 'scale_factor': 0.18215, 'use_ema': False, 'only_mid_control': False, 'use_VAEdownsample': True, 'use_lastzc': True, 'use_imageCLIP': True, 'use_pbe_weight': True, 'u_cond_percent': 0.2, 'use_attn_mask': False, 'control_stage_config': {'target': 'cldm.warping_cldm_network.NoZeroConvControlNet', 'params': {'image_size': 32, 'in_channels': 13, 'hint_channels': 3, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'cond_first_ch': 4}}, 'unet_config': {'target': 'cldm.warping_cldm_network.StableVITON', 'params': {'image_size': 32, 'in_channels': 13, 'out_channels': 4, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'dim_head_denorm': 1}}, 'first_stage_config': {'target': 'ldm.models.autoencoder.AutoencoderKL', 'params': {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig': {'double_z': True, 'z_channels': 4, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}, 'lossconfig': {'target': 'torch.nn.Identity'}}}, 'validation_config': {'ddim_steps': 50, 'eta': 0.0, 'scale': 1.0}, 'cond_stage_config': {'target': 'ldm.modules.image_encoders.modules.FrozenCLIPImageEmbedder'}, 'img_H': 512, 'img_W': 384}}, 'dataset_name': 'VITONHDDataset', 'default_prompt': '', 'log_images_kwargs': {'unconditional_guidance_scale': 5.0}}
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 1039.33 M params.
beta scheduler name : linear
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
learnable vector gene
here
/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
0/1
Data shape for PLMS sampling is (1, 4, 64, 48)
Running PLMS Sampling with 50 timesteps
PLMS Sampler:   0%|          | 0/50 [00:00<?, ?it/s]198.235.24.10 - - [22/May/2024 09:18:50] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
PLMS Sampler:   2%|â         | 1/50 [00:43<35:08, 43.03s/it]PLMS Sampler:   4%|â         | 2/50 [00:59<21:45, 27.20s/it]PLMS Sampler:   6%|â         | 3/50 [01:13<16:47, 21.44s/it]PLMS Sampler:   8%|â         | 4/50 [01:28<14:23, 18.78s/it]PLMS Sampler:  10%|â         | 5/50 [01:42<12:44, 16.99s/it]PLMS Sampler:  12%|ââ        | 6/50 [01:56<11:41, 15.95s/it]PLMS Sampler:  14%|ââ        | 7/50 [02:09<10:55, 15.25s/it]PLMS Sampler:  16%|ââ        | 8/50 [02:22<10:06, 14.44s/it]PLMS Sampler:  18%|ââ        | 9/50 [02:35<09:31, 13.93s/it]PLMS Sampler:  20%|ââ        | 10/50 [02:48<09:07, 13.68s/it]PLMS Sampler:  22%|âââ       | 11/50 [03:01<08:42, 13.40s/it]PLMS Sampler:  24%|âââ       | 12/50 [03:15<08:40, 13.70s/it]PLMS Sampler:  26%|âââ       | 13/50 [03:29<08:31, 13.83s/it]PLMS Sampler:  28%|âââ       | 14/50 [03:44<08:26, 14.06s/it]PLMS Sampler:  30%|âââ       | 15/50 [03:58<08:07, 13.92s/it]PLMS Sampler:  32%|ââââ      | 16/50 [04:12<07:53, 13.93s/it]PLMS Sampler:  34%|ââââ      | 17/50 [04:25<07:38, 13.89s/it]PLMS Sampler:  36%|ââââ      | 18/50 [04:39<07:20, 13.77s/it]PLMS Sampler:  38%|ââââ      | 19/50 [04:52<07:03, 13.68s/it]PLMS Sampler:  40%|ââââ      | 20/50 [05:04<06:34, 13.13s/it]PLMS Sampler:  42%|âââââ     | 21/50 [05:18<06:25, 13.28s/it]PLMS Sampler:  44%|âââââ     | 22/50 [05:31<06:08, 13.18s/it]PLMS Sampler:  46%|âââââ     | 23/50 [05:43<05:50, 13.00s/it]PLMS Sampler:  48%|âââââ     | 24/50 [05:56<05:37, 12.98s/it]PLMS Sampler:  50%|âââââ     | 25/50 [06:09<05:22, 12.90s/it]PLMS Sampler:  52%|ââââââ    | 26/50 [06:22<05:12, 13.03s/it]PLMS Sampler:  54%|ââââââ    | 27/50 [06:35<04:58, 12.97s/it]PLMS Sampler:  56%|ââââââ    | 28/50 [06:48<04:42, 12.85s/it]PLMS Sampler:  58%|ââââââ    | 29/50 [07:01<04:31, 12.94s/it]PLMS Sampler:  60%|ââââââ    | 30/50 [07:13<04:15, 12.77s/it]PLMS Sampler:  62%|âââââââ   | 31/50 [07:26<04:05, 12.90s/it]PLMS Sampler:  64%|âââââââ   | 32/50 [07:40<03:55, 13.09s/it]PLMS Sampler:  66%|âââââââ   | 33/50 [07:53<03:39, 12.93s/it]PLMS Sampler:  68%|âââââââ   | 34/50 [08:06<03:28, 13.03s/it]PLMS Sampler:  70%|âââââââ   | 35/50 [08:18<03:12, 12.84s/it]PLMS Sampler:  72%|ââââââââ  | 36/50 [08:31<02:58, 12.77s/it]PLMS Sampler:  74%|ââââââââ  | 37/50 [08:44<02:49, 13.03s/it]PLMS Sampler:  76%|ââââââââ  | 38/50 [08:58<02:36, 13.07s/it]PLMS Sampler:  78%|ââââââââ  | 39/50 [09:11<02:23, 13.09s/it]PLMS Sampler:  80%|ââââââââ  | 40/50 [09:23<02:09, 12.91s/it]PLMS Sampler:  82%|âââââââââ | 41/50 [09:37<01:58, 13.12s/it]PLMS Sampler:  84%|âââââââââ | 42/50 [09:51<01:46, 13.31s/it]PLMS Sampler:  86%|âââââââââ | 43/50 [10:04<01:33, 13.33s/it]PLMS Sampler:  88%|âââââââââ | 44/50 [10:16<01:17, 12.98s/it]PLMS Sampler:  90%|âââââââââ | 45/50 [10:29<01:05, 13.10s/it]PLMS Sampler:  92%|ââââââââââ| 46/50 [10:43<00:53, 13.30s/it]PLMS Sampler:  94%|ââââââââââ| 47/50 [10:57<00:40, 13.52s/it]PLMS Sampler:  96%|ââââââââââ| 48/50 [11:11<00:26, 13.45s/it]PLMS Sampler:  98%|ââââââââââ| 49/50 [11:24<00:13, 13.38s/it]PLMS Sampler: 100%|ââââââââââ| 50/50 [11:37<00:00, 13.29s/it]PLMS Sampler: 100%|ââââââââââ| 50/50 [11:37<00:00, 13.95s/it]
62.67.51.161 - - [22/May/2024 09:30:08] "GET /run_SV/2024-05-22_09-17-47 HTTP/1.1" 200 -
103.56.61.144 - - [22/May/2024 18:30:33] "[35m[1mGET / HTTP/1.0[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
103.56.61.144 - - [22/May/2024 18:30:34] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
103.56.61.144 - - [22/May/2024 18:30:34] "[33mGET /robots.txt HTTP/1.1[0m" 404 -
103.56.61.144 - - [22/May/2024 18:30:35] "[33mGET /.well-known/security.txt HTTP/1.1[0m" 404 -
199.45.154.69 - - [22/May/2024 23:02:03] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
199.45.154.69 - - [22/May/2024 23:02:11] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
199.45.154.69 - - [22/May/2024 23:02:13] code 505, message Invalid HTTP version (2.0)
199.45.154.69 - - [22/May/2024 23:02:13] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
198.235.24.221 - - [22/May/2024 23:38:43] "[35m[1mGET / HTTP/1.0[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.122 - - [22/May/2024 23:40:00] code 400, message Bad request version ('Ã\x14Ã')
167.94.138.122 - - [22/May/2024 23:40:00] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03Ã$\x86Ã·Â¨Ã\x09Â£o\x95>\x036Ã¥Â´l\x95~Ã¢Ã¿Ã¾ÃÃ½GÃ Ã¹Ã¨Â²1Â²\x9bÃ¨ Ã¾\x16Ã\x0bÃ¾Ã½[(ÃQjtGZÃ®\x1d,NÂ³\x95Ãª]Ã7Ãµ)Â¹dÃ£(Â b\x00&ÃÂ¨ÃÂ©Ã/Ã0Ã+Ã,Ã\x13Ã\x09Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
167.94.138.122 - - [22/May/2024 23:40:03] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.122 - - [22/May/2024 23:40:06] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.122 - - [22/May/2024 23:40:07] code 505, message Invalid HTTP version (2.0)
167.94.138.122 - - [22/May/2024 23:40:07] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
167.94.138.43 - - [22/May/2024 23:51:55] code 400, message Bad request version ('Ã\x14Ã')
167.94.138.43 - - [22/May/2024 23:51:55] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03\x8bÂ¥Ã¶\x9f}tÂ¨\x98Ã¥XXÃÃªSÂºÂ¼aFÂ§Ã¢Ã«\x8f\x0fyÃ\x84\x17\x04Ã\x1a\x0eÂ® Â«\x98Â¶Ãª\x0f\x1f2gÃÂ¾\x04\x0cjÃÃ¶yÃ_Ã\x14'"p\x0f*k">\x8d=_\x82\x00&ÃÂ¨ÃÂ©Ã/Ã0Ã+Ã,Ã\x13Ã\x09Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
167.94.138.43 - - [22/May/2024 23:51:59] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.43 - - [22/May/2024 23:52:02] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.138.43 - - [22/May/2024 23:52:02] code 505, message Invalid HTTP version (2.0)
167.94.138.43 - - [22/May/2024 23:52:02] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
138.68.167.171 - - [23/May/2024 00:09:33] code 400, message Bad request version ('Ã#ÃÂ¬ÃÂ®Ã+Ã')
138.68.167.171 - - [23/May/2024 00:09:33] "[35m[1m\x16\x03\x03\x01\x9c\x01\x00\x01\x98\x03\x03,G\x83WÃÃ¿Â«\x16ÂºÂªÃ\x0fÃ·!Â¹Â¤\x18Âª\x05\x10Âµ]%Ã\x1d\x16\x8cf\x9eXÃ¶A }\x98(fÃ Â´\x80hÂ¹\x85\x14u\x13\x87\x1eoÃ¬Â±\x9e\x94ÃS2Ã^E\x1c-|\x9dÂ¬\x00\x8czz\x00\x16\x003\x00gÃ\x9eÃÂ¢\x00\x9e\x009\x00kÃ\x9fÃÂ£\x00\x9f\x00E\x00Â¾\x00\x88\x00Ã\x00\x9aÃ\x08Ã\x09Ã#ÃÂ¬ÃÂ®Ã+Ã[0m" HTTPStatus.BAD_REQUEST -
138.68.167.171 - - [23/May/2024 00:09:34] code 400, message Bad request syntax ('\x16\x03\x03\x01\x9c\x01\x00\x01\x98\x03\x03')
138.68.167.171 - - [23/May/2024 00:09:34] "[35m[1m\x16\x03\x03\x01\x9c\x01\x00\x01\x98\x03\x03[0m" HTTPStatus.BAD_REQUEST -
138.68.167.171 - - [23/May/2024 00:09:34] code 400, message Bad request version ("Ã¦Â©'Â¿KXÃÃ Â¥\x8cKAR\x01Â¾ÃÂ²:Â¶,\x00H\x1a\x1aÃ\x12Ã\x07Ã\x14\x13\x01\x13\x02ÃÂ©ÃsÃrÃ,ÃÂ¯Ã\xadÃ$Ã")
138.68.167.171 - - [23/May/2024 00:09:34] "[35m[1m\x16\x03\x03\x01X\x01\x00\x01T\x03\x03Ãº,\x9f,\x0bÃ±w\x02,1ÃÃ`\x15ÃÂ½Â®;wÃ@Ã\x9e)ÃtÃº\x99iÃÃ´Ã Ã£[Â«Â³6pÃ»\x99\x1a\x95\x12\x0cÃ¦Â©'Â¿KXÃÃ Â¥\x8cKAR\x01Â¾ÃÂ²:Â¶,\x00H\x1a\x1aÃ\x12Ã\x07Ã\x14\x13\x01\x13\x02ÃÂ©ÃsÃrÃ,ÃÂ¯ÃÂ­Ã$Ã[0m" HTTPStatus.BAD_REQUEST -
138.68.167.171 - - [23/May/2024 00:09:34] code 400, message Bad request version ("Â´Âµ\x9b\x00FÂºÂºÃ\x13Ã'Ã/Ã\x14Ã(Ã0Ã`ÃaÃvÃwÃÂ¨\x13\x05\x13\x04\x13\x03Ã\x13Ã\x11\x00")
138.68.167.171 - - [23/May/2024 00:09:34] "[35m[1m\x16\x03\x03\x01J\x01\x00\x01F\x03\x03Ã¡ÃÂ¢Sw\x1aÂº?AÃÂ¶\x1aÃ\x97\x80\x07jSÂªUP\x81ÃÂ¹=\x03Ã°\x14\x0c\x8dÃ¨C ÃÂºÃ\x1e\x7f\x12`<\x18\x1eaBÃ¾N7\x14Ã¯\x97Ã­\x80Ã¬\x0d\\\x1c(`Ã}\x1dÂ´Âµ\x9b\x00FÂºÂºÃ\x13Ã'Ã/Ã\x14Ã(Ã0Ã`ÃaÃvÃwÃÂ¨\x13\x05\x13\x04\x13\x03Ã\x13Ã\x11\x00[0m" HTTPStatus.BAD_REQUEST -
138.68.167.171 - - [23/May/2024 00:09:34] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x03\x01s\x01\x00\x01o\x03\x03\x15F\x8b.0Ã\x03y[\x95Ã³GXÂ©Ã¹\xadÃKÂ¸\x07W\x19:Â¢zt7Â¼Ã¿Ã¬ÃÂ¿')
138.68.167.171 - - [23/May/2024 00:09:34] "[35m[1m\x16\x03\x03\x01s\x01\x00\x01o\x03\x03\x15F\x8b.0Ã\x03y[\x95Ã³GXÂ©Ã¹Â­ÃKÂ¸\x07W\x19:Â¢zt7Â¼Ã¿Ã¬ÃÂ¿ @WÃ­\x99Ã¶6-e1RÃÃ)Ã:~Ã°\x9eOÃ£\x7fIÂ¸\x1aLr\x05Â«5Ã\x81#\x00\x8aÃ\x12Ã\x13Ã\x07Ã'Ã\x14Ã/\x13\x01Ã\x14\x13\x02Ã(ÃÂ©Ã0ÃsÃ`ÃrÃaÃ,ÃvÃÂ¯ÃwÃÂ­ÃÂ¨Ã$\x13\x05Ã[0m" HTTPStatus.BAD_REQUEST -
138.68.167.171 - - [23/May/2024 00:09:34] code 400, message Bad request version ('Ã#ÃÂ¬ÃÂ®Ã+Ã')
138.68.167.171 - - [23/May/2024 00:09:34] "[35m[1m\x16\x03\x02\x01\x9c\x01\x00\x01\x98\x03\x02)TXh$ÂµeÂ®\x11@Ã±Ã«KÃ±Ã¥5Ã"R'\x9cÃ*Â¨E\x97Ã·a\x9eÃ®ÃÃ© 'ÃtUÃÃ©Ã¹\x81\x80\x10@{Â³tÃ³\x85Ã²7Â±.ÂµÂ´<_Ã¯\x9b~|\x92Ã\x81a\x00\x8czz\x00\x16\x003\x00gÃ\x9eÃÂ¢\x00\x9e\x009\x00kÃ\x9fÃÂ£\x00\x9f\x00E\x00Â¾\x00\x88\x00Ã\x00\x9aÃ\x08Ã\x09Ã#ÃÂ¬ÃÂ®Ã+Ã[0m" HTTPStatus.BAD_REQUEST -
138.68.167.171 - - [23/May/2024 00:09:34] code 400, message Bad request version ('Ã#ÃÂ¬ÃÂ®Ã+Ã')
138.68.167.171 - - [23/May/2024 00:09:34] "[35m[1m\x16\x03\x01\x01Â©\x01\x00\x01Â¥\x03\x03Ã¹Â³\x0f\x8d\x8c\x1cÃ¾Ã£\x9fÂ£nÂ¶\x19Ãª\x0eÃÂ®ÃÃ¯qeuÂ¸\x1c5UmÂ¹Ã`\x1bw \x19Ã\x8eÃ\x83C`ÃÃ\x81|ÃÃkÂ¿ Â¹Â¦Ãsh@\x80\x8a\x18\x01-\x1c\x02tÃI\x00\x8cÃÃ\x00\x16\x003\x00gÃ\x9eÃÂ¢\x00\x9e\x009\x00kÃ\x9fÃÂ£\x00\x9f\x00E\x00Â¾\x00\x88\x00Ã\x00\x9aÃ\x08Ã\x09Ã#ÃÂ¬ÃÂ®Ã+Ã[0m" HTTPStatus.BAD_REQUEST -
138.68.167.171 - - [23/May/2024 00:09:35] code 400, message Bad request version ('Ã\x9c\x00<\x00/\x00')
138.68.167.171 - - [23/May/2024 00:09:35] "[35m[1m\x16\x03\x01\x01Â©\x01\x00\x01Â¥\x03\x03\x9ecFÃ3^GPÂ²=7TÃ­Ãc\x13\x91\x98Ã\x14<\x82Ã~Â¤\x16ÂªÂ¥1Ãt\\ >)\x95"ÃªSÃ­ÃÃ°Â¦z\x0d\x9cs@e\x1e\x11\x86Ã·\x90ÃÃ¹\x86\x80\x14\x7fÃ\x08Â´Ã®Â¢\x00\x8cÃÃ\x00\x05\x00\x04\x00\x07\x00Ã\x00\x84\x00Âº\x00A\x00\x9dÃÂ¡Ã\x9d\x00=\x005\x00\x9cÃÂ Ã\x9c\x00<\x00/\x00[0m" HTTPStatus.BAD_REQUEST -
138.68.167.171 - - [23/May/2024 00:09:35] code 400, message Bad request version ('Ã#ÃÂ¬ÃÂ®Ã+Ã')
138.68.167.171 - - [23/May/2024 00:09:35] "[35m[1m\x16\x03\x01\x01\x9f\x01\x00\x01\x9b\x03\x03-"\x87O8qfÂ§Â¸ÂºÃ¿Ã¯Ã,Â¾VÂ¼Ã¶SeÂ«\x7frÂ¥Â¤4Â¨VÃ\x8dÂ°Ã ?Â­\x07>7-u+ds=Ã©Ã¬Ã\x0eÃ½Ã£ÃÃµÂ¥\x8aÃ\x12\x9a[2\x06Âµ\\Â¦\x90p\x00\x82::\x00\x16\x003\x00gÃ\x9eÃÂ¢\x00\x9e\x009\x00kÃ\x9fÃÂ£\x00\x9f\x00E\x00Â¾\x00\x88\x00Ã\x00\x9aÃ\x08Ã\x09Ã#ÃÂ¬ÃÂ®Ã+Ã[0m" HTTPStatus.BAD_REQUEST -
138.68.167.171 - - [23/May/2024 00:09:35] code 400, message Bad request version ("jÂ¢Ã;Ã3Â³Ã¡\x97EÃbÂ¾'Â©uAN!umÂ·Â·Â´JÃ\x8a\x9cÃ²Â°Â´\x93\x00\x8aÃ\x12Ã\x13Ã\x07Ã'Ã\x14Ã/\x13\x01Ã\x14\x13\x02Ã(ÃÂ©Ã0ÃsÃ`ÃrÃaÃ,ÃvÃÂ¯ÃwÃ\xadÃÂ¨Ã$\x13\x05Ã")
138.68.167.171 - - [23/May/2024 00:09:35] "[35m[1m\x16\x03\x01\x01\x8e\x01\x00\x01\x8a\x03\x03Â¿Ã¯Â°Ã/\x97Ã-\x1aZ\x1b\x12\x1cBHÃ·Ã¨Ã£Â«Ã\x17\x19 'Ã¾\x81UN\x1dÂ¯Â³Ã jÂ¢Ã;Ã3Â³Ã¡\x97EÃbÂ¾'Â©uAN!umÂ·Â·Â´JÃ\x8a\x9cÃ²Â°Â´\x93\x00\x8aÃ\x12Ã\x13Ã\x07Ã'Ã\x14Ã/\x13\x01Ã\x14\x13\x02Ã(ÃÂ©Ã0ÃsÃ`ÃrÃaÃ,ÃvÃÂ¯ÃwÃÂ­ÃÂ¨Ã$\x13\x05Ã[0m" HTTPStatus.BAD_REQUEST -
155.133.23.58 - - [23/May/2024 00:22:06] "[35m[1mGET / HTTP/1.0[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.145.99 - - [23/May/2024 01:41:08] code 400, message Bad request version ('Ã\x14Ã')
167.94.145.99 - - [23/May/2024 01:41:08] "[35m[1m\x16\x03\x01\x00Ã®\x01\x00\x00Ãª\x03\x03\x1b7T\x92Ã\x88JÃÃÃ\x9a ÃÃ\x98Ã\x1cDÃ³\x06Ã¤mK5BÃkÃ\x09w;Â¹ Ã®uÃº\x9fcÃ\x88\x87\x15UT\x16\x82\x16Ã¦DJZKÂ¦+t\x05\x98\x9f\x7f\x9c\x812ÃÃ-\x00&ÃÂ¨ÃÂ©Ã/Ã0Ã+Ã,Ã\x13Ã\x09Ã\x14Ã[0m" HTTPStatus.BAD_REQUEST -
167.94.145.99 - - [23/May/2024 01:41:11] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.145.99 - - [23/May/2024 01:41:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
167.94.145.99 - - [23/May/2024 01:41:14] code 505, message Invalid HTTP version (2.0)
167.94.145.99 - - [23/May/2024 01:41:14] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
198.235.24.223 - - [23/May/2024 06:16:20] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/media/HDD2/VITON/StableVITON_git/StableVITON/api.py", line 34, in index
    return render_template('index.html')
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/media/HDD2/VITON/anaconda/envs/StableVITON/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
67.70.237.204 - - [23/May/2024 09:34:52] code 400, message Bad request version ("\x01\x8e\x19Â§YX4,Ã®Ã°Ã\x97hoÃ§4\x08tÂ»mÃ¢\x13Â¯ÃaxÃ\xadÃ\x99ÂµT\x00Ã\x13\x01\x13\x02\x13\x03\x13\x04\x13\x05Ã,Ã0\x00Â£\x00\x9fÃÂ©ÃÂ¨ÃÂªÃÂ¯Ã\xadÃÂ£Ã\x9fÃ]ÃaÃWÃS\x00Â§Ã+Ã/\x00Â¢\x00\x9eÃÂ®ÃÂ¬ÃÂ¢Ã\x9eÃ\\Ã`ÃVÃR\x00Â¦Ã$Ã(\x00k\x00jÃsÃw\x00Ã\x00Ã\x00m\x00ÃÃ#Ã'\x00g\x00@ÃrÃv\x00Â¾\x00Â½\x00l\x00Â¿Ã")
67.70.237.204 - - [23/May/2024 09:34:52] "[35m[1m\x16\x03\x01\x01Ã\x01\x00\x01Â¼\x03\x03\x89\x90.Ã°ÃÃ¬UÂ°\x92Â£ÃÃÂ¶i\x05Â¢\x08\x92Ã\x8cÂ¶Ã¨Ã\x89@\x1de\x0cÃ¶\x7f\x10\x1f \x01\x8e\x19Â§YX4,Ã®Ã°Ã\x97hoÃ§4\x08tÂ»mÃ¢\x13Â¯ÃaxÃÂ­Ã\x99ÂµT\x00Ã\x13\x01\x13\x02\x13\x03\x13\x04\x13\x05Ã,Ã0\x00Â£\x00\x9fÃÂ©ÃÂ¨ÃÂªÃÂ¯ÃÂ­ÃÂ£Ã\x9fÃ]ÃaÃWÃS\x00Â§Ã+Ã/\x00Â¢\x00\x9eÃÂ®ÃÂ¬ÃÂ¢Ã\x9eÃ\\Ã`ÃVÃR\x00Â¦Ã$Ã(\x00k\x00jÃsÃw\x00Ã\x00Ã\x00m\x00ÃÃ#Ã'\x00g\x00@ÃrÃv\x00Â¾\x00Â½\x00l\x00Â¿Ã[0m" HTTPStatus.BAD_REQUEST -
192.241.200.14 - - [23/May/2024 11:07:12] "[33mGET /v2/ HTTP/1.1[0m" 404 -
45.95.169.184 - - [23/May/2024 16:37:49] code 400, message Bad HTTP/0.9 request type ('\x00\x00\x00\x11\x00\x00\x01Ã©\x00\x01\x00\x00\x00Ã¿Ã¿Ã¿Ã¿\x01\x00\x00\x00\x00\x00\x00\x00')
45.95.169.184 - - [23/May/2024 16:37:49] "[35m[1m\x00\x00\x00\x11\x00\x00\x01Ã©\x00\x01\x00\x00\x00Ã¿Ã¿Ã¿Ã¿\x01\x00\x00\x00\x00\x00\x00\x00\x0c\x02\x00\x00\x00\x10MyCustomAssembly\x05\x01\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
